version: '3'
services:
  golang-skeleton-web:
    container_name: golang-skeleton-web
    build: '.'
    ports:
      - '8080:8080'
      - '40000:40000'
    depends_on:
      - 'mongo-skeleton-web'
  mongo-skeleton-web:
    container_name: mongo-skeleton-web
    image: mongo:6-jammy
    volumes:
      - ./dbdata:/data/db
    ports:
      - '10018:27017'